= Context
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

== Barcelona City Council

Approved in October 2016, the Barcelona *Digital City Plan* (PBCD) is a cross cutting Plan which aims to guarantee a coherent, standard technology policy within the City Council, in the areas of Government and City, Enterprises and Social Entities and Citizens.

The PBCD must ensure that digital technology and innovation act as facilitators in the fulfilment of fair and efficient public policies geared towards covering better the needs of citizens and boosting their capabilities, to create greater quality public services, with the optimum allocation and use of public re-sources and talent.

Three strategic areas have been defined within the PBCD, with the following objectives (Figure 1):

image::open-digit-p9-axes-{lang}.svg[FIGURE 1, align="center"]

The *Barcelona City Council’s Digital Transfor-mation Plan* (PTDA) is the comprehensive roadmap for ICT projects for this term of office, and for each Manager’s Office, in accordance with political priorities. This plan also includes projects for updating technology and adapting it to the new legal framework established under Act 39/2015 of 1 October, on Common Administrative Procedures for Public Authorities (LPCAP).

== Legal Framework

Law 39/2015 of 1st October, on Common Administrative Procedures for Public Authorities (LPACAP), which comprehensively promotes digital administration - not just citizen relations but also the electronic management of administrative procedures, electronic documents and files, interoperability, etc. - defines a new legal framework which requires profound changes to be made in the provision of public services and, as a consequence, in municipal organisation and their information systems.

Note that in addition to compliance with the LPACAP, we can find other legal texts in the regulatory context of the EU and in Spanish and Catalan legislation that have to be responded to:

* The EU eGovernment Action Plan 2016-2020, that aims to remove existing digital barriers to the Digital Single Market and to prevent further fragmentation arising in the context of the modernisation of public administrations.

* •	The new EU General Data Protection Regulation (GDPR), approved in May 2016, which the entire public authority must adapt to and comply with.

* Act 19/2014, of 29 December, on transparency, access to public information and good government. The aim behind this Act is to provide citizens with information on the actions of regional public authorities and control and transparency in the destination of public money.

* •	Act 11/2007, of 22 June, on citizens’ electronic access to public services, known as LAESCP.
In this context, free software, open standards and open source technologies are considered the best option for the development of a technological model for eGovernment, tailored to the specific needs and objectives of public authorities, based on the strategic criteria of transparency, control, security, interoperability, access and conservation of information, economics, reuse of data and cooperation between organisations, which closed technologies can hardly compete against.

* Royal Decree 4/2010, of 8 January, regulating the National Interoperability Scheme, which includes the security criteria and recommendations, standardisation and conservation of information, and the formats and applications that public authorities must take into account to ensure an appropriate level of organisational, semantic and technical interoperability for data, information and services that they manage in exercising their powers and to prevent discrimination against citizens on the grounds of their choice of technology.

== New Trends in the development of agile digital services, technological sovereignty and ethical data management

Given the current situation where changes come about at an incredibly fast pace and changes within changes are occurring, we to develop and implement models for digital services that will help us to adapt to these transformations.
This is even more the case in the information and communication technologies (ICT) sector, where speed and agility are essential in the face of change.
Hence the appearance of agile methodologies, given the difficulties and occasional failures experienced with traditional methods of project management.

By “agile methodologies” we mean a group of methods, started under the “Agile Manifesto”footnote:[_Manifest àgil - font http://agilemanifesto.org_] of 2001, applied to the creation of software that bases its development on an iterative cycle, where needs and solutions evolve through collaboration between the various teams involved in the project.
Agile methodologies promote a disciplined approach to project management that encourages constant revision and adaptation to the needs of the users and to the changes.
These methods provide an organised system that allows and facilitates teamwork and self organisation and helps to reduce development times.

////
Falta parraf
////

As for technological and data sovereignty, we can confirm that free software is “technically feasible, economically sustainable and socially fair”1 footnote:[_Jordi Mas al seu llibre homònim (Col·lecció “Manuals i Formularis”, 15)_].
This is reflected in specific benefits to the local authority.

* It is *technically viable* because it allows us to reuse existing free software projects, reducing the implementation efforts required to cover our own needs.
Every IT company, regardless of its size, depends on free software to some degree.
The fact that the local authority wishes to make direct use of this is a logical step.

The freedom to choose tools also means the freedom to choose the provider for maintaining and developing them.
Working with open formats and standards does away with the need to depend on large companies and enables permanent access to the information generated.

Participating directly in the community provides access to the consolidated knowledge of other entities, enabling them to contribute through documentation, code or shared experiences implementing projects in the authority.

* It is economically sustainable because it removes the requirement for user licenses and cuts down on costs.
Such a reduction in costs does not mean a loss of quality or security.
On the contrary, it can enable projects that would not be possible with proprietary software, and keep systems up to date and protected at the lowest possible cost.

These cost savings can be reinvested in suitable hardware for new tools or items that require additional resources.
Thus the local authority is showing responsibility towards public money and responsibly managing it.

Freedom to select providers without restrictions can boost the reinvestment of public funds into the region while benefiting the local economy.
Generating a virtuous circle where any SME, cooperative or freelance can offer their services, under equal conditions.
In a country where 90% of businesses are either small or medium-sized, this opens up a large window of opportunity.

It also provides freedom to choose the municipal management of the IT infrastructure, without the need for expertise in exclusive, high-cost tools.
The public and private jobs generated will be available to more of the territory’s professionals.

* It is *socially fair* because it guarantees the fundamental rights of citizens.
Access to the source code and its collective control helps us to know what it does and to ensure that it does not have any gateway or security vulnerabilities.
Data privacy and security are ensured.

Such benefits either do not exist or require much higher economic and social costs with proprietary software.

Royal Decree 4/2010 (see more in section 04.2) has existed since 2010, and makes it mandatory for Public Authorities to use open formats when sharing information with citizens.
The list of formats is not a choice for each public entity, but rather a list of standards that is specified and regularised for interoperability.
As such, Public Authorities will use open standards to guarantee independence in the choice of technological alternatives made by citizens and public authorities, preserving documents over time, and adaptation to progress in technology.

Where appropriate, documents, electronic services and applications made available by public authorities to citizens and other public authorities will be displayable, accessible and functionally operational, under conditions which support the principle of technological neutrality and avoid discrimination against citizens on the grounds of their choice of technology.

Data were of little and limited interest until recently, although computer processing capacities have reached the stage where we can now harness and reuse data.
At the same time, there has been an exponential growth in the amount of such data.
For security reasons, this situation makes it crucial both to control and release these data, for the purposes of boosting their reuse, with the conviction that public data can generate business and social improvement for the entire population.
Combining free tools and open data puts us in a whole new ball game, where transparency and a willingness to share and work on a community basis create a new organisation of public administration.

== Agile methodologies and free software in other public authorities

*Agile methodologies*

While Agile methodologies have mainly been implemented in private enterprise, their use is not unknown in public administration.
Since 2012 footnote:[https://www.gov.uk/service-manual/agile-delivery]the British government Has been pro-moting them, as well as the US Department of Defense. A good example is the development of a new British service to manage vehicle inspections (MOTs).

Closer to home, the Regional Government of Andalusia in 2010, put out to tender the service for the development of the website entitled “DEVELOPMENT OF THE CONSUMER RESPONDS WEBSITE”, using the Scrum agile methodology, certainly the most popular of the agile methodologies in software development.
In 2010, the regional government of the Canary Islands also put out to tender the maintenance service for the IT records system in the field of tourism using these methodologies.

Vitòria Gasteiz City Council published an invitation to tender in 2013, for “the procurement of a redesigned municipal website using adaptive design”.
The technical specifications stated that the methodology to be used was SCRUM.

March 2017 saw the Provincial Council of Badajoz commence procedures to procure development and implementation services for new functionalities and the technological evolution of its current management applications, also using the agile SCRUM methodology.

Public-private institutions including the Thyssen Museum, Hospital Clínic de Sant Carlos in Madrid and its Smart Health Lab and the Tax Agency are starting to use and apply agile techniques such as Lean Government.

Barcelona started introducing agile methodologies in 2013 for the development and management of municipal websites and it will now be the first big city in southern Europe to launch and implement this type of methodology on a global basis within the City Council.

*Open technologies*

Regarding experiences in free software at a local level, public authorities have for a long time now started implementing Open Technology policies and deploying free and open-source based services.
Regionally, we have the exam-ple of the University of Lleida (UDL), which is a pioneering public university in the use of free software in Catalonia, together with the Open University of Catalonia (UOC).
It has been using free systems for years, yielding excellent results.
A new team, one of whose goals was to promote the use of free software, took over the vice-chancellor’s office in 2003 and commenced a migration process for all the systems.
In 2006, the Generalitat of Catalonia published its own Free Software roadmap.

The University of Murcia signed up for the Open Academic Environment (OAE) in 2014,an international initiative to create a free software platform which allows the development of an open collaborative academic network.
This project is headed by the University of Cambridge, and the University of Murcia was the first Spanish university to take part in it.
The university started migrating its computers to Linux in 2015.
This resulted in savings of €100,000 in user licenses and another €300,000 by not having to renew equipment.
Recently Barcelona City Council released the code of Sentilo, its sensor data management platform, as free software and won an EU award for Sharing and Reuse.

A nivell europeu, el Ministeri d'Exteriors alemany, al 2003, va iniciar la migració dels seus 11.000 ordinadors a GNU/Linux i a aplicacions de programari lliure.
Això ha permès reduir considerablement els costos si els comparem amb altres ministeris.
Es pretén que la migració es dugui a terme a les 230 ambaixades i consolats repartits arreu del món.
L'equip de TI de la Gendarmerie Nationale francesa, per tal de poder oferir un servei responsable i rendible a nivell nacional i per tal de reduir els creixents costos d'infraestructura de TI, va decidir a l'any 2004, revisar el seu entorn basat en Microsoft existent.
Es va migrar a OpenOffice, Firefox i es va fer una actualització de PC's cap a Ubuntu.
Això va provocar un estalvi de 2 milions d'euros anuals només en drets de llicència, també s'ha produït una reducció dràstica de les despeses en maquinari.

Italia, al 2014, va escollir el software lliure com la primera opció per a l'Administració Pública.
Van crear un document titulat “_Guias para la evaluación comparativa (de software)_”, on s'aprèn un mètode a seguir per prendre la decisió correcta a l'hora d'escollir un programari.
El cas italià és molt important perquè es preocupa no només per la norma, sinó per la seva implementació.
La guia elaborada per l'Agència Digital Italiana es va redactar amb participació tant de la Free Software Foundation Europe, com dels representants de diferents empreses de programari privatiu.

Les polítiques de tecnologies obertes per a l'administració pública europea son recolzades per l'acció de la Comissió Europea, que publica a la seva pròpia llicència lliure per a Administracions Públiques, la llicència EUPL, i centralitza els esforços en la seva plataforma “_Join Up_” on trobem literalment centenars d'experiències de migració o desenvolupament de programari lliure a les administracions europees.

The government in Brazil launched several digital inclusion projects in parallel in several areas, based on the installation of call centres, whose aim was to reduce digital exclusion, increase professional skills, distribute free software and increase public participation in new technologies.
Free software has played a fundamental role in the creation of these centres and is enabling those who have just arrived in the digital world to do so with legal software.

Al 2004, el govern de Malàisia va iniciar el Pla mestre per a fomentar, adoptar i desenvolupar l'ús del programari lliure al sector públic, posant en marxa l'_Open Source Competency Center_ (OSCC) que va establir-se com un centre de referència nacional per a dirigir i donar suport a l'aplicació del programari lliure a l'Administració.

Més recentment, al 2013, la Índia va invertir en ordinador amb programari lliure (Ubuntu) per als seus estudiants.
És un dels programes més importants del món per a portàtils patrocinats pel govern, es porta a terme amb 1,5 milions d'ordinadors portàtils.

Respecte als formats i dades obertes, el 23 de juny del 2006, el Consell de Ministres de Bèlgica a Brussel·les va aprovar la decisió de requerir que tots els intercanvis documentals en els serveis del Govern Federal Belga es produeixin en formats oberts i estàndards.
Per tant, i expressament, només OpenDocument (ODF) va estar acceptat com a tal estàndard en aquesta decisió.

Al 2010 va néixer el projecte Open Data BCN, implantant el portal a l'any 2011, que té com a principal objectiu aprofitar al màxim els recursos públics disponibles, exposant la informació generada o custodiada per organismes públics, permetent el seu accés i reutilització per al bé comú i per al benefici de persones i entitats interessades.
El projecte que s'emmarca dins de l'estratègia Barcelona Ciutat Digital, es basa en els principals estàndards i recomanacions internacionals, adoptant les característiques, de dades obertes per defecte, qualitat i quantitat d'informació, dades per a tothom, dades per a la millora de la governança i promoció a la innovació.

Tal i com hem pogut veure en els casos que s'han descrit, des de fa molts anys les administracions estan desplegant un procés de transformació cap a metodologies àgils i programari lliure.
En algunes d'elles ja s'han pogut demostrar de forma clara els seus beneficis, tant a nivell d'estalvi econòmic i mitigació de la obsolescència tecnològica amb la incorporació de programari lliure, com en la millora de la productivitat i adaptació a través de les metodologies àgils.
