= Context
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

== Barcelona City Council

Approved in October 2016, the Barcelona *Digital City Plan* (PBCD) is a cross cutting Plan which aims to guarantee a coherent, standard technology policy within the City Council, in the areas of Government and City, Enterprises and Social Entities and Citizens.

The PBCD must ensure that digital technology and innovation act as facilitators in the fulfilment of fair and efficient public policies geared towards covering better the needs of citizens and boosting their capabilities, to create greater quality public services, with the optimum allocation and use of public re-sources and talent.

Three strategic areas have been defined within the PBCD, with the following objectives (Figure 1):

image::open-digit-p9-axes-{lang}.svg[FIGURE 1, align="center"]

The *Barcelona City Council's Digital Transfor-mation Plan* (PTDA) is the comprehensive roadmap for ICT projects for this term of office, and for each Manager's Office, in accordance with political priorities. This plan also includes projects for updating technology and adapting it to the new legal framework established under Act 39/2015 of 1 October, on Common Administrative Procedures for Public Authorities (LPCAP).

== Legal Framework

Law 39/2015 of 1st October, on Common Administrative Procedures for Public Authorities (LPACAP), which comprehensively promotes digital administration - not just citizen relations but also the electronic management of administrative procedures, electronic documents and files, interoperability, etc. - defines a new legal framework which requires profound changes to be made in the provision of public services and, as a consequence, in municipal organisation and their information systems.

Note that in addition to compliance with the LPACAP, we can find other legal texts in the regulatory context of the EU and in Spanish and Catalan legislation that have to be responded to:

* The EU eGovernment Action Plan 2016-2020, that aims to remove existing digital barriers to the Digital Single Market and to prevent further fragmentation arising in the context of the modernisation of public administrations.

* •	The new EU General Data Protection Regulation (GDPR), approved in May 2016, which the entire public authority must adapt to and comply with.

* Act 19/2014, of 29 December, on transparency, access to public information and good government. The aim behind this Act is to provide citizens with information on the actions of regional public authorities and control and transparency in the destination of public money.

* •	Act 11/2007, of 22 June, on citizens' electronic access to public services, known as LAESCP.
In this context, free software, open standards and open source technologies are considered the best option for the development of a technological model for eGovernment, tailored to the specific needs and objectives of public authorities, based on the strategic criteria of transparency, control, security, interoperability, access and conservation of information, economics, reuse of data and cooperation between organisations, which closed technologies can hardly compete against.

* Royal Decree 4/2010, of 8 January, regulating the National Interoperability Scheme, which includes the security criteria and recommendations, standardisation and conservation of information, and the formats and applications that public authorities must take into account to ensure an appropriate level of organisational, semantic and technical interoperability for data, information and services that they manage in exercising their powers and to prevent discrimination against citizens on the grounds of their choice of technology.

== New Trends in the development of agile digital services, technological sovereignty and ethical data management

Given the current situation where changes come about at an incredibly fast pace and changes within changes are occurring, we to develop and implement models for digital services that will help us to adapt to these transformations.
This is even more the case in the information and communication technologies (ICT) sector, where speed and agility are essential in the face of change.
Hence the appearance of agile methodologies, given the difficulties and occasional failures experienced with traditional methods of project management.

By “agile methodologies” we mean a group of methods, started under the “Agile Manifesto”footnote:[_Manifest àgil - font http://agilemanifesto.org_] of 2001, applied to the creation of software that bases its development on an iterative cycle, where needs and solutions evolve through collaboration between the various teams involved in the project.
Agile methodologies promote a disciplined approach to project management that encourages constant revision and adaptation to the needs of the users and to the changes.
These methods provide an organised system that allows and facilitates teamwork and self organisation and helps to reduce development times.

////
Falta parraf
////

As for technological and data sovereignty, we can confirm that free software is “technically feasible, economically sustainable and socially fair”1 footnote:[_Jordi Mas al seu llibre homònim (Col·lecció “Manuals i Formularis”, 15)_].
This is reflected in specific benefits to the local authority.

* It is *technically viable* because it allows us to reuse existing free software projects, reducing the implementation efforts required to cover our own needs.
Every IT company, regardless of its size, depends on free software to some degree.
The fact that the local authority wishes to make direct use of this is a logical step.

The freedom to choose tools also means the freedom to choose the provider for maintaining and developing them.
Working with open formats and standards does away with the need to depend on large companies and enables permanent access to the information generated.

Participating directly in the community provides access to the consolidated knowledge of other entities, enabling them to contribute through documentation, code or shared experiences implementing projects in the authority.

* It is economically sustainable because it removes the requirement for user licenses and cuts down on costs.
Such a reduction in costs does not mean a loss of quality or security.
On the contrary, it can enable projects that would not be possible with proprietary software, and keep systems up to date and protected at the lowest possible cost.

These cost savings can be reinvested in suitable hardware for new tools or items that require additional resources.
Thus the local authority is showing responsibility towards public money and responsibly managing it.

Freedom to select providers without restrictions can boost the reinvestment of public funds into the region while benefiting the local economy.
Generating a virtuous circle where any SME, cooperative or freelance can offer their services, under equal conditions.
In a country where 90% of businesses are either small or medium-sized, this opens up a large window of opportunity.

It also provides freedom to choose the municipal management of the IT infrastructure, without the need for expertise in exclusive, high-cost tools.
The public and private jobs generated will be available to more of the territory's professionals.

* It is *socially fair* because it guarantees the fundamental rights of citizens.
Access to the source code and its collective control helps us to know what it does and to ensure that it does not have any gateway or security vulnerabilities.
Data privacy and security are ensured.

Such benefits either do not exist or require much higher economic and social costs with proprietary software.

Royal Decree 4/2010 (see more in section 04.2) has existed since 2010, and makes it mandatory for Public Authorities to use open formats when sharing information with citizens.
The list of formats is not a choice for each public entity, but rather a list of standards that is specified and regularised for interoperability.
As such, Public Authorities will use open standards to guarantee independence in the choice of technological alternatives made by citizens and public authorities, preserving documents over time, and adaptation to progress in technology.

Where appropriate, documents, electronic services and applications made available by public authorities to citizens and other public authorities will be displayable, accessible and functionally operational, under conditions which support the principle of technological neutrality and avoid discrimination against citizens on the grounds of their choice of technology.

Data were of little and limited interest until recently, although computer processing capacities have reached the stage where we can now harness and reuse data.
At the same time, there has been an exponential growth in the amount of such data.
For security reasons, this situation makes it crucial both to control and release these data, for the purposes of boosting their reuse, with the conviction that public data can generate business and social improvement for the entire population.
Combining free tools and open data puts us in a whole new ball game, where transparency and a willingness to share and work on a community basis create a new organisation of public administration.

== Agile methodologies and free software in other public authorities

*Agile methodologies*

While Agile methodologies have mainly been implemented in private enterprise, their use is not unknown in public administration.
Since 2012 footnote:[https://www.gov.uk/service-manual/agile-delivery]the British government Has been pro-moting them, as well as the US Department of Defense. A good example is the development of a new British service to manage vehicle inspections (MOTs).

Closer to home, the Regional Government of Andalusia in 2010, put out to tender the service for the development of the website entitled “DEVELOPMENT OF THE CONSUMER RESPONDS WEBSITE”, using the Scrum agile methodology, certainly the most popular of the agile methodologies in software development.
In 2010, the regional government of the Canary Islands also put out to tender the maintenance service for the IT records system in the field of tourism using these methodologies.

Vitòria Gasteiz City Council published an invitation to tender in 2013, for “the procurement of a redesigned municipal website using adaptive design”.
The technical specifications stated that the methodology to be used was SCRUM.

March 2017 saw the Provincial Council of Badajoz commence procedures to procure development and implementation services for new functionalities and the technological evolution of its current management applications, also using the agile SCRUM methodology.

Public-private institutions including the Thyssen Museum, Hospital Clínic de Sant Carlos in Madrid and its Smart Health Lab and the Tax Agency are starting to use and apply agile techniques such as Lean Government.

Barcelona started introducing agile methodologies in 2013 for the development and management of municipal websites and it will now be the first big city in southern Europe to launch and implement this type of methodology on a global basis within the City Council.

*Open technologies*

Regarding experiences in free software at a local level, public authorities have for a long time now started implementing Open Technology policies and deploying free and open-source based services.
Regionally, we have the exam-ple of the University of Lleida (UDL), which is a pioneering public university in the use of free software in Catalonia, together with the Open University of Catalonia (UOC).
It has been using free systems for years, yielding excellent results.
A new team, one of whose goals was to promote the use of free software, took over the vice-chancellor's office in 2003 and commenced a migration process for all the systems.
In 2006, the Generalitat of Catalonia published its own Free Software roadmap.

The University of Murcia signed up for the Open Academic Environment (OAE) in 2014,an international initiative to create a free software platform which allows the development of an open collaborative academic network.
This project is headed by the University of Cambridge, and the University of Murcia was the first Spanish university to take part in it.
The university started migrating its computers to Linux in 2015.
This resulted in savings of €100,000 in user licenses and another €300,000 by not having to renew equipment.
Recently Barcelona City Council released the code of Sentilo, its sensor data management platform, as free software and won an EU award for Sharing and Reuse.

On a European level, Germany's Foreign Ministry started migrating its 11,000 computers to GNU/ Linus and free software applications in 2003.
This enabled a considerable reduction in costs compared to those of other ministries.
The aims are for 230 embassies and consulates around the world to migrate to open technologies.
The Gendarmerie Nationale's IT team decided to review their existing Microsoft based environment in 2014 so it could offer a responsible and profitable service at a national level and reduce its growing IT infrastructure costs.
It migrated to OpenOffice and Firefox and its PCs were upgraded to Ubuntu.
This resulted in savings of 2 million euros annually in license rights alone as well as a drastic reduction in hardware expenses.

In 2014, Italy chose free software as the first choice for its public administration.
It created a document titled, “Guides for comparative assessment (of software)”, which teaches people a method to follow to make the right decisions when choosing software.
The Italian example is very important as it is concerned with not just regulations but also their implementation.
The guide developed by the Italian Digital Agency was drafted with both the Free Software Foundation Europe and representatives from several proprietary software companies taking part.

Open technology policies for the European public administrations are supported by the action of the European Commission, that publishes to his own free licence for Public Administrations, the EUPL, and centralises efforts in his “Join Up” platform where one finds literally hundreds of experiences of migration or development of free software for the European public authorities.

The government in Brazil launched several digital inclusion projects in parallel in several areas, based on the installation of call centres, whose aim was to reduce digital exclusion, increase professional skills, distribute free software and increase public participation in new technologies.
Free software has played a fundamental role in the creation of these centres and is enabling those who have just arrived in the digital world to do so with legal software.

Malaysia's public administration launched its Master Plan on 16 June 2004 to promote, adopt and develop the use of free software in the public sector.
The Open Source Competency Centre (OSCC) went into operation.
The OSCC became established as a national benchmark centre for managing and supporting the application of free software within the administration.

More recently, in December 2013, India invested in computers with free software (Ubuntu) for its students.
This is one of the most important programmes in the world for government-endorsed laptops, installed on 1.5 million laptop computers..

As regards open data and standards, on 23rd June 2006, the Belgian Council of Ministers in Brussels approved the decision to require all document exchanged between services provided by the Federal Belgian Government to take place in open and standard formats.
So only OpenDocument (ODF) was expressly accepted as such a standard in this decision.

The Open Data BCN project was created in 2010 and its portal installed in 2011, the main objective of which was to take full advantage of the public resources available, displaying information generated or held by public bodies, allowing access to and the reuse of data for the common good and for the benefit of the people and entities concerned.
Part of the Barcelona Digital City strategy, the project is based on the main international standards and recommendations, adopting the features of open data by default, quality and quantity of information, data for everyone, data for the improvement of the governance and the promotion of innovation.

As we have seen in the examples described above, authorities have been undergoing a process of transformation towards agile methodologies and free software for years.
Some of these have already demonstrated clear benefits, not just in financial savings and mitigating technological obsolescence through the implementation of free software but also in improving productivity and adaptation through agile methodologies.
