= Lines of action
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

Lines of action have been established for each of the topics mentioned in the previous section which will be elaborated upon below, together with their associated actions.

== Agile and user-centred digital services

The introduction of agile development methodologies is essential for the development of user-centred digital services.

The following actions were carried out during the first quarter of 2017:

4 workshops were organised (tools, agile management, skills acquisition, culture and organisation) with internal employees from the IMI, developers, service managers, sectoral managers and directors.

By implementing these methodologies, we will achieve the agreed lines of action:

* BCN will transform 20 new digital services following the Digital Service Standards and the Technology Code of Conduct (all the new services are listed in section 0.8).

* •	We will focus more on the end-user, giving them a leading role in *decision-making*.

* We will *reduce development times* and simultaneously improve technical quality.

* We will *offer more public value* while maintaining control of the developments.

Based on the lines of action identified, we will be able to:

* Transform the organisational culture, promoting collaboration and transparency, while being more flexible and delivering more public value.

* Implement continuous improvement by implementing practices in the organisation that require system-based processes to be improved.

== Technological sovereignty and migration to free software

Technological sovereignty will be achieved through migration to free software, the deployment of open standards, changes in public procurement to promote open source software and the identification of migration opportunities to open architecture in the short term.

The lines of actions here are:

* *Ensuring that 70% of investments* in new software developments go towards open sour-ce software.

* Making *10 solutions* developed by Barcelona City Council available to other municipalities and administrations.

* Incorporating open *corporate workstations* which function using open systems and programmes into the municipal systems.

During the first half of 2017, the following actions were carried out:

* Identify opportunities for development and/or migration to architectures and open systems in the short term.

* Preparation of a migration and development plan for free and open source code.

* Definition of guidelines for publishing and sharing software and content of the City Council under free software and content licenses.

* Introduce into public procurement processes the promotion of the creation, use and reuse of free and open source software.

* Introduce guidelines at corporate level for the use of open standards for technologies, data and other information in the city.

Based on the lines of action identified, we will achieve the following:

* An increase in technological sovereignty.

* Improvement of our image and positioning among society.

* Reduction in development costs (low).

* Reduction maintenance costs (effective).

* Reduction of technology evolution costs (notable when we introduce new functionalities developed by the community).

* Reduction in costs of migration to new solutions (important).

Flagships projects in this area, with a total budget of 21.5 million euros and a timetable ranging from the first quarter of 2017 until the end of the second quarter of 2019, are included in the Open Source Migration Plan (Annex 12.5).

* Migration of corporate e-mail to open tech-nologies

* Adaptation of the Windows workstation (Windows 10) with a set of free software applications.

* Adoption of development tools for applications based on open technologies.

* Open workstation and desktop.

* Mobile ID / e-ID.

* New services developed in open source

== Responsible and ethical data strategy

Data are of considerable importance in the municipal and city environment and there is a clear need to define and put into operation a new cross-cutting municipal government model for reinforcing sovereignty.
Given its importance, the City Council will devote a government measure to express the data management policy and its implementation throughout all the units of the City Council.

Here, we indicate the action lines and projects that will fall under the scope of this forthcoming measure, an essential element of the Digital Transformation Plan.

The lines of actions here are:

* *Designing and carrying out* initiatives to adapt to the new GDPR for processing personal data in Barcelona City Council.

* *Defining and implementing* new processes which allow privacy and security to be incorporated by default, in the design of new computer applications.

* *Establishing the level of proactive control* required by the new regulation.

* Defining the role of the municipal office of data analytics and the *Chief Data Officer*.

* Creating a *Chief Data Analytics Office*, bringing new capabilities for privacy related data improvement and analysis.

* Creating a *Data Challenges* programme to involve SMEs and companies in devising data-driven applications for solving the city's challenges.

We worked on the following initiatives during the first quarter of 2017:

* Establishing new rules for data governance.

* Defining the open architecture of data.

* Creating platforms for big data analysis for public policies and services.

* Creating a guide for ethical and responsible uses of data, guaranteeing privacy and sovereignty.

Based on the lines of action that have been identified, we will be able to:

* Improve effectiveness and efficiency.

////
* Millorar la presa de decisions.
////
* Democratise access to data.

* Create new and improved public services.

* Achieve greater democratic quality, respecting citizens' rights, data protection and access to information.

* Generate Transparency and accountability.

* Regain citizen's trust.

The total budget for the flagship projects in this area is 2.3 million euros and their timetable runs from the first quarter of 2017 up to the middle of the first quarter of 2019.

* CityOS Services (pollution, mobility, tourism).

* Ecology dashboard.

* Barcelona Housing Observatory (OHB).

* DCODE: An EU wide project to develop a block-chain based architecture for data sovereignty.

== New procurement model

Through achieving the main objective of the new procurement model, outlined in section 06.5, we can guarantee technological and data sovereignty, promote technological innovation and lever social and economic change.

The lines of action here are:

* *New Procurement Framework:* Conceptualising a new orientation in the procurement process.

* *ICT Procurement Guide:* A guide which gives an overview of the municipal strategy and facilitates the application of various measures.

* *Implementing the Innovative Procurement Guide:* A guide which orientates its readers towards considering innovation as a fundamental element which is inseparable from and boosts sustainable procurement.

* *Drafting standard procurement documents:* for standardisation and agility in procurement.

* *Creation of the Digital Marketplace:* A space for continuous dialogue and interaction between providers, citizens and the City Council.

* *Communication and dissemination:* Dissemination actions for the transformation process and municipal strategy over procurement.

The following actions were carried out during the first quarter of 2017:

* Creating the guide for the procurement of technology and the guide for innovative procurement.

* The development of these standard procurement documentation.

* Work sessions with the ICT sector to fortify the measures linked to the procurement of technology

* Surveys to build a digital market platform (Marketplace).

The total budget for the flagship project in this area is 22 million euros.
The timetable runs from the beginning of the second quarter of 2017 to the end of the first quarter of 2018.

* Digital Marketplace.

== Culture and organisation of the change

For the transformation of the existing teams there is a plan to train internal staff, with workshops aimed at the organization, training and culture, agile management and learning new tools.

In parallel, in the first half of 2017, a process to cover 64 new positions for computer technicians (superior and middle level) has also begun, through 2 job boards.
This process should last until the end of 2017 and the incorporation of people will take place during the first half of 2018.

We are also planning an organic restructuring that provides for the creation of 16 new departments, in accordance with differentiation criteria for sectoral areas by technical specialization, which will reinforce management, delegate responsibilities for middle management and the coordination of the different working groups.

To finish, the emblematic projects that have been pointed out in each one of the lines of action and that are detailed in the section 08, are part of the Mandate Plan that consists of 3 plans: Sectoral, Legal and Technological, as is set out in the following diagram (Figure 4).

We also show how progression has been made, and consumption of the 2017 budget.

image::open-digit-p30-roadmap-{lang}.svg[_FIGURE 4: Composition and execution of the Mandate Plan_, align="center"]
