= Success metrics and results
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

The purpose behind success metrics is to provide tools for understanding whether the actions taken by the City Council have helped it to reach its goals and what changes need to be made to ensure these goals are achieved.
A well-designed measurement responds to specific performance-related questions and allows decisions to be made to improve data-based services.

The digitisation programme's progress will be monitored through iconic projects.
Their degree of performance (performance %) and the budget implemented will be measured.
The progress of the programme's various action lines and the initiatives they entail will be measured by means of progress metrics and indicators specific to each initiative: proportion of contracts performed under fast methodologies, budget allocated to fast projects, budget aimed at freeware and open-code project, development and launch times for new services, quantity of defects detected in the developments, number of iterations, etc.

The knowledge level of the transformation process that is acquired from the various municipal areas will be measured.
At the same time, the degree of satisfaction for each area will be assessed with the new digital services developed, through a periodic survey.
The adaptation of the services to the needs of the “business”, the degree of their updating, their usability, accessibility, degree of innovation and response time will be measured in that same survey.

Another important metric that will be used for monitoring the programme's success will be the availability of digital public services.
The following diagram (Figure 6), shows the results regarding the availability and provision of services for the first half of 2017.

image::open-digit-p34-pki-{lang}.svg["_FIGURE 6: Service availability indicators_, align="center"]

Finally, human resources is one of the main indicators that will be used for measuring the progress of this programme.
The process that is being carried out in this area, as well as the planning, is depicted in the following image (Figure 7).

image::open-digit-p35-resources-{lang}.svg[_FIGURE 7: Human Resources Plan indicators_, align="center"]
