= The open digitisation and agile service delivery programme
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

== Mission statement and principles

*Public services currently must be designed to be “digital first”, putting citizens at the centre of the design process and contributing more public value.*
*Services must be constructed in a more agile and open way and must be simpler, more modular and more interoperable.*
*At the same time, we must avoid creating dependencies on vendors and suppliers of specific proprietary solutions, hence the need to promote the development, use and reuse of free and open source software and open standards.*
*Services must be usable and accessible to everyone, including citizens with low levels of digital skills and people with disabilities.*

The *Open Digitisation and Agile Service Development Programme* provides a focus on digital services to revitalise the City Council as a benchmark for technical innovation and excellence.
It will bring quality digital services, adapted to the needs of citizens and orientated towards safeguarding citizens' right to privacy (data privacy), services which, by making use of free and open source software and open standards, will end the dependency on proprietary formats, products and solutions (technological sovereignty).

Digital public services need to become true assets of today's society, with their reuse made possible in other cities.
That is why initiatives are needed in the area of public procurement of technology which can foster a more mature approach to the provision of technology to the public sector, by proposing multisupplier contracting models that promote competition and diversity of suppliers, enable the adoption of new innovative technologies and move away from big contracts, by creating a new market for open and collaborative SMEs.

What's more, the programme generates profiles and capacities in user centred design and agile methodologies, to bring the flexibility to and accelerate the development and delivery of these services, while opening public procurement and increasing its transparency, simplicity and objectivity, thereby providing a route to technological and data sovereignty.

The programme will establish a framework for an open architecture and designs based on open standards, through a series of incremental changes with a clear governance structure, results orientated, with clear measurements and indicators and a shared roadmap.

As a starting point, the programme defines the basic principles to guide the way for developing new services.
These principles are contained in the Decalogue titled *Our Digital Service Standards* (see Annexe 12.1):

* *Multi disciplinary teams for services:* Setting up a multidisciplinary sustainable team that can design, build and operate a service, led by a qualified senior service manager, that has decision making responsibilities.

* *Beginning with the needs of users:* Users needs have to be understood and re-search carried out to develop more knowledge on who the service users are and what this means for the service design.

* *Using agile development methodologies and iterative building methods.*
Building the service using agile and iterative user centred methodologies.

* *Reducing the burden on citizens.*
Existing information will be used in the municipal systems during new interactions with citizens, with interoperation with other public authorities to gather the required information and avoid having to ask the citizens to provide it again.
Unnecessary documents will be removed in the digital version of the service and the City Council will ensure that citizens give their consent for their personal documents to be used.

* *Following the guidelines on visual de-sign and accessibility.*
A coherent service will be built based on the experiences of users of the rest of Barcelona City Council, in terms of existing visual design and accessibility guidelines.

* *Having a plan available for people who need digital assistance.*
Use of digital services will be encouraged among all users and plans made for people who cannot access digital services for whatever reason without support.
As for the provision of essential services, the City Council will need to ensure that it adapts to citizens who do not have digital devices.

* *Considering security, privacy and ethical aspects.*
An assessment will be made of which user data and information will be provided or stored in the digital service, taking into account the level of security, legal obligatoins, privacy issues and the risks associated with the service.
(consulting with experts if necessary).

* *Open source software and open standards will be used.*
Open source software and open standards will be used whenever possible.
Likewise, all new code will be open source and reusable so that it can be published under appropriate licenses.

* *Having a plan available for digitisation.*
We will ensure that all digital services provide citizens with the digital means to produce, sign and authenticate their documents.
In the event that there are citizens who do not have their own digital resources, we will have to ensure there is a service available at the City Council for digitising these documents.

* *Making a plan for going offline in case of unforeseen circumstances.
A plan will be available in case the digital service is temporarily down, as users expect an online service to be available 24 hours a day, 365 days a year.

* *Tools, systems and services will be evaluated.*
Assessments will be made to ensure that the technological code of conduct is followed and the associated technical risks are understood.

* *Reusing the existing infrastructure and shared functions as far as possible.*
A coherent service experience will be created that enables time and resources to be saved by eliminating the need for existing functionalities to be rebuilt.

* *Defining a plan for managing the change for the transition of the service.*
There will be continuity service plans to facilitate the transition between the current non digital service and the new digital service.
Any interruption to citizens' access to the service has to be avoided.

* *Feedback and continuous user assessment.*
A plan will be implemented under which we will be continuously open to feedback from users and carrying out usability tests to gather users opinions continuously and thereby be able to improve the service.

* *Measuring and publishing the service's results.*
Performance indicators of the service will be identified, establishing a reference point for each measurement and making a plan for enabling improvements.

* *Making a maintenance and servicing plan for the digital service.*
There will be a “response and escalation” plan to minimise service interruption when incidents occur.

Barcelona City Council has published an information poster with further details for publishing our digital service standards.
This poster can be seen in Annexe 12.1 accompanying this measure.

== Priorities and methods for creating digital services

The following four main action areas have been identified for the purposes of the digitisation programme's optimum development and obtaining open, interoperable, ethical and agile digital services for the public:

* Agile methodologies in the delivery of digital services

* Technological Sovereignty (free software and open standards)

* Sovereignty and the responsible use of data

* New public procurement model

While the programme is transversal, and both the IMI and City units are involved, each area of action will be led by a different team.
It is based on our services standards and a new code of technological practices supported by a guide for the introduction of agile methodologies, and a guide for the transition to free and open source software (software, hardware, systems), the guides on open public procurement and of innovative procurement complete the documentary framework supporting the programme.
The next government measure will set out the management of data for the City of Barcelona and will express the strategy of responsible and ethical use of data and its concrete implementation.

This is an internal transformation so the process must be led by the City Council itself, involving its own staff, working to develop the capacity for acquiring skills and results.
Support will occasionally be necessary from external experts in the sector who, along with training and experience from the new agile team, will provide help in understanding the skills and competencies that will be needed in the immediate future.
A procurement plan and a skills-creation programme will be implemented to meet these needs and keep the transformation alive.
This process will lead to major internal involvement.

The whole transformation process will be carried out under the same agile philosophy.
So, the programme will begin with a discovery stage followed by successive iterations that will gradually allow the new culture and new practices to be introduced.

New practices will be developed and refined based on real projects, which we will call exemplary or flagship projects (described in section 08 of this document).
The new methodology will gradually extend to all projects where such practices are applicable.

== The current Situation

The discovery stage in Barcelona City Council began in September 2016, with support from external experts.
Four work groups were created in which more than 40 workers from several municipal areas participated.
These groups worked for 4 months with help from 4 external experts to generate a base that would help to drive change.

Throughout 2017, as many as 3 sessions were held with the sector (free software and open technologies, agile digital services and public procurement of technology), involving more than 200 representatives of the City and industry.
Internally, between April and June this year, within the Transformation Plan, four workshops were organised (tools workshop, management workshop, training workshop and an organisation workshop).

In the first quarter of 2017, the agile methodology was applied to its first real project, the municipal management dashboard.
This was used for defining the actions for introducing agile methodologies to the City Council, choosing the most appropriate projects to begin applying them, identifying the necessary external support needed and defining the internal training plan and the organisation and necessary tools for new practices.

Between 2016 and 2017, the City Council launched *Decidim.Barcelona* and *Sentilo*, applications that been developed as its own free software.

* *Decidim.barcelona* is the most advanced free software to be developed by Barcelona City Council and has enabled one of the biggest open, transparent and traceable participatory processes in the world among its citizens in the collective construction of the city's strategic plan.
Its mission is to provide support, open up and broaden participation and democracy in Barcelona in the coming years, by advancing towards a greater ability for collaboration between the City Council and citizens, greater decision making freedom for people, with particular emphasis placed on the collective dimension, and ultimately, in creating and delivering social power.
Principles that are still in force today in many free software communities.
Decidim is deployed in 9 cities in Catalonia and the Basque Country, as well as the French Commission for National Debate.

* As regards Barcelona's sensor platform, *Sentilo* was fully developed with free software and is made available globally through the Sentilo Community.
As with Decidim, this platform is already being used in several cities and by various public authorities and a large number of cities and companies have also expressed their interest in trying it out and creating technologies that are compatible with Sentilo.
The main objective of Sentilo is to provide a functional, interoperable and easily extendible platform to every city in the world that so wants it, by sharing public investment in development under the free software model.
Sentilo is the first experience of Barcelona in creating a community around a free software project, a place that also aims to be a meeting point where cities and companies can collaborate to enhance the platform, provide support and develop business around Sentilo.
Organisations besides Barcelona currently using Sentilo are: Terrassa, Reus, Cambrils, Barcelona Provincial Council, the Catalan Water Agency (ACA), Barcelona Metropolitan Area (AMB) and the Dubai Municipality.

In the field of open data, the Open Data BCN portal, the open data service of the Barcelona City Council must be highlighted.
It is a multi language and easy to access space, where users can find a data set (dataset catalogs) that the Barcelona City Council makes available in a reusable way.
The information is classified into 5 major issues (administration, population, territory, economy and company and city and services), each with its corresponding subthemes, allowing filtering.
Since the beginning of July 2017, it has the “re-users” section, a community space aimed on the one hand at developers, to facilitate the work of this more technical group in the use of data, and on the other, “views and applications”, a section that gives visibility to projects carried out with data from the Portal.

Barcelona already has experience and has started the path indicated by the Digital Transformation Plan, exceeding expected benefits.
The moment has come to reinforce and formalize it.
This measure and its expression through various documents that are the result of this discovery process, clearly establish the foundations, standards, and main processes of open digitization and the rapid development of services:

* The digital services standard (see Annexe 12.1).

* The code of technological practices (see Annexe 12.2).

* Agile methodologies in Barcelona City Council (see Annexe 12.3).

* Technology Sovereignty Guide (see Annexe 12.4)

* Action plan for free and open source software (see Annexe 12.5).

* Guide for the public procurement of ICTs: Technology Acquisition Manual with ethical and open clauses (see Annexe 12.6).

* Guide for innovative public procurement.

The guides, which accompany this government measure as supporting documents, will be published as a comprehensive body of work and continuously improved throughout the process of agile transformation during this term of office.

As indicated above, the guidelines on data will be developed through a future specific measure on the use of data in the City Council, giving it the importance it deserves.
