= Flagship projects within the course of action
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

The changes to be introduced as a result of the development of this open digitisation and development of agile services programme, are being carried out gradually through a series of projects outlined in the previous section, which is why we call them flagship projects.

These will be pioneer projects for the application of the new practices, whether they are agile development technologies or using open source software solutions, applying open standards or implementing the recommendations derived from the new data strategy.

This section presents all the flagship projects within this digitisation programme, with a brief description of each:

. *Municipal Management Dashboard.*
In addition to the development of a dashboard for the government team, a free application for citizens will also be developed that shows a summary of strategic indicators and provides data on the city council services with management indicators for their projects, progress made on accomplishing government commitments, citizen's ratings, etc.
This service is an important step towards having more transparency in municipal management and public scrutiny.

. *Citizen Help and Information Portal.*
The procedures portal for citizens and companies in Barcelona will be renewed to simplify access and use and reduce the documentation required by the rules of administrative procedure.
Citizens will notice a clear improvement in the usability of the portal's digital services and a simplification in the procedures.

. *Mobile Municipal Services.*
Reducing the number of web apps.
This is about simplifying how the portal functions to improve usability.
Obsolete applications will be removed, applications will be consolidated, new open source tools will be introduced and open data-use increased.
A set of new web apps using adaptive design will be developed and made available to citizens.

. *Decidim Barcelona.*
Development of Stage 3 of the citizen participation platform which includes multi-consultation functions.
This will improve the participatory services that the City Council has made available to citizens.

. *Information system for social rights.*
Part of the new information system from the Manager's Office for Social Rights will be developed using new methodologies.
This will speed up the development of new digital services and the efficiency of related public services.

. *ASIA.*
A new calendar of events and facilities in the city.
This is currently one of the digital services most used by citizens.
Its performance and usability will be improved.

. *Barcelona Sports Institute's Information System.*
Some of the applications that make up the new information system of the Barcelona Sports Institute will be developed with the new agile methodologies.
Citizens should notice an improvement in the services provided by this institute.

. *E-Government.*
A series of digital applications and services to adapt administrative procedures to the new legal framework.
Some of these applications will be constructed with the new agile development methodology.
The most tangible benefit of this will be the simplification of municipal procedures for citizens, who will appreciate a reduction in bureaucracy and an improvement in response times.

. *Corporate email migration.*
The Microsoft Exchange email servers will be replaced with an open source alternative.
Email clients will also be migrated by Microsoft Outlook will be kept in place (for 20% of users).
The service's improvement will have an impact on the entire municipal organisation.

. *New workstation with free software.*
The project will replace the maximum number of proprietary applications currently used in the different work stations of the City Council for applications based on free and open source software, but without replacing the platform or Microsoft Windows operating system.

. *Adopting tools for the development of open technology based applications.*
The intention is to implement a framework that allows the development of open source applications and management tools for development in open source technologies.

. *Open desktop.*
Workstations that currently have proprietary applications and operating systems will gradually be migrated towards workstations with 100% open source products.

. *Mobile-ID Identifier/ e-ID.*
The mobile identifier currently has 18,000 users and is used more than 2,000 times each week.
The service will be updated and new authentication mechanisms incorporated.
The main beneficiaries of this service are citizens, who will have a tool to facilitate the use of the various digital services offered by the City Council.

. *Services developed in open source.*
Various applications used by the City Council will be developed internally and/or externally in free and open source code.
These applications or services will be offered to the community so that any public administration can use them, so that any developer or ICT company can develop and add new features.
Note that the City Council is already using open source applications such as the Open Data portal, the Internet of Things platform, Sentilo, the image bank (BIMA) and the Decidim.Barcelona participatory platform.

. *City OS Services.*
This is an advanced data-analytics platform with a consolidated view of city information, based on free and open source products.
It will be offered to the community to detect problems, shorten response times and improve public services.
The various management offices and service directorates will be able to use this data platform for carrying out more accurate analyses of information and thereby issue better public policies.

. *Ecology dashboard.*
A dashboard will be developed which integrates the areas of environment, urban planning, infrastructures, mobility and urban services to improve decision making processes.

. *The Barcelona Housing Observatory (OHB).*
A repository of big data specialised in housing will be created that will allow data to be analysed and for public policies to be developed to combat the current housing issues.

. *DCODE.*
This is a European pilot project being developed in Barcelona and Amsterdam to manage data sovereignty in a shared economy.
The technical solutions being developed in this project will work to improve services for citizens, making them more secure while further safeguarding data ownership and control.

. *Digital Marketplace.*
The creation of a digital marketplace to facilitate the access small businesses have to public procurement processes.

. *IRIS.*
Development of the new version of the multi channel service for Incidents, Claims and Suggestions that manages the requests for services, notices, incidents and claims of citizens since 2003.
This new version will be developed entirely in open source software and will be transferred to the community.

The schedule for execution of flagship projects related to the application of agile methodologies and the use of software and open standards is as follows.

image::open-digit-p33-schedule-{lang}.svg[_FIGURA 5: Calendari d'execució_, align="center"]
