= Themes and objectives
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
include::{partialsdir}/README.adoc[tag=metadata]

If the objectives of the Open Digitisation: Free Software and Agile Service Development Programme are to be achieved, work must be carried out to deliver agile digital services centred on users, through three main action areas:

* Strengthening *technological sovereignty*, through the adoption of free software and open public procurement.

* Adopting agile methodologies, introducing an agile work framework.

* Improving *data governance*, through a new data strategy.

This will be achieved through a series of actions in each of the areas that make up the programme (Figure 2)

image:open-digit-p20-areas-{lang}.svg[_FIGURE_ 2: align="center"]

== Agile and user-centred digital services

We need to change the way we design and build new public services, by considering them as digital from the outset, in other words, “digital first”.
They need to be designed by putting the citizen at the centre and built in an agile and gradual way to reduce waiting times for their launches.
Municipal workers who are responsible for the service, as well as citizens, have to play an active role in the design, construction and maintenance of these services.
This process of change, inspired by the examples of Anglo-American administrations, will provide new public services that are better adapted to the real needs of citizens, while reducing development time.

Agile digital services form the starting point for achieving the objectives of this digitisation programme.
These services allow citizens, businesses and organisations to interact with the city government in an easier, faster and more economical way.
These simple, fast and interactive services will be available at all times and anywhere and which will have been designed to satisfy the needs of citizens and municipal workers.
We will develop services considered digital from the outset and easily adaptable to new needs.

////
            REVISAR Si HO FIQUEM

Please consult the Digital Services Standard (Annex 12.1) as the reference document on this topic.
////

== Agile Methodologies

Agile methodologies will provide the tools needed for designing, building and delivering digital services to citizens and municipal workers in a flexible and efficient way.

The introduction of an agile working framework will require:

* The creation of multidisciplinary teams

* An global overview of the entire service life cycle

* The gradual introduction of agile methodologies

* The involvement of the whole organisation

* Carrying out of pilot projects

* Continuous improvement based on contributions from all the parties.

Starting from these action lines, as listed in point 07, we will be able to:

* Put more focus on the end-user and empower users in the decision making process.

* Shorten development time and simultaneously improve technical quality.

* Increase the frequency of improvements and implement continuous improvements.
Deliver more frequently and reliably, to advance the return on investment, and standardise continuous improvement based on short monitoring and adaptation cycles.

* Put the focus on collaboration and transparency.

* Increase the orientation towards value by keeping control of developments, being more flexible and delivering more value to end-users.

The total budget for the flagship projects in this area is 7 million euros.
The timetable for these projects runs from the middle of the second quarter of 2017, up to the end of the second quarter of 2019.

These projects are:

* Municipal Management Dashboard.

* Citizen Help and Information Portal.

* Mobile Municipal Services.

* Decidim.Barcelona.

* Information system for social rights.

* ASIA.

* Municipal Sports Institution’s Information System.

* E-Government.

== Technological sovereignty and Open Technologies

Barcelona requires technological sovereignty, and is decisively tackling the transition to free software and open standards for this purpose.
The best practices in this area are being studied and a migration plan will be designed and a code of best practices on open technologies established to guide internal transformation and promote third-party reuse and sharing of software and the development and/or use of shared government solutions.
The transition to open source software and open standards is aimed at reinforcing technological sovereignty (see Annex 12.5).

Systems based on free software and open standards offer multiple benefits:

* *Transparency:* the source code can be examined and audited by anyone who has sufficient technical knowledge, without the explicit permission of the developer or the City Council.
Without this property it is difficult to rely on the neutrality and security of an increasing number of governmental and administrative processes that are implemented through software, such as voting processes.

* *Interoperability:* the use of open formats and standards allows different systems, possibly from different manufacturers, to work together without any legal and technical obstacles.
This opens up possibilities for integration between different systems, for example to reuse data and improve processes.
It also guarantees that citizens are not obliged to use technological solutions from specific providers to interact with the Administration.

* *Sovereignty:* transparency and interoperability greatly reduce dependence on commercial strategies of manufacturers.
The user, in this case the City Council, can decide with greater freedom what systems to evolve, resize or replace, as well as establish its own policies regarding security, privacy, updates and access to systems.
In the case of organizations, sovereignty also fosters control over their own processes and the generation and conservation of knowledge.

* *Flexibility:* systems can be better adapted to the needs of users and users, and can be adapted and extended as these needs evolve, without depending on any particular provider.
Not only is development more flexible, also the evaluation of alternatives is easier and cheaper, and the conditions of operation and maintenance can be modified more easily.

* *Sustainability:* interoperability allows you to replace those parts of the systems that need to be renewed without the data being ever useless.
Greater sovereignty also implies a lower risk of obsolescence of any part of the systems, including hardware.
Collaboration (between people and entities) that promote free licenses can be a great help in making a system more stable and lasting.

* *Efficiency:* factors such as the cost savings associated with the payment of licenses, increased competition among suppliers, a lower risk of obsolescence, and the possibility of sharing costs with other users and entities, make free and standard-based open source software the best option to guarantee the efficiency that the law demands from the Administration. The huge base of existing combinable software allows us to reach solutions in many domains that are adapted to end users with a low use of resources.

* *Reliability and security:* the independence from commercial strategies makes users able to demand higher quality services and take advantage of all the corrections and improvements provided by a community of users and developers of each tool.

* *Innovation:* transparency, and a fortunate combination of collaboration and competition, make free software an enormously fertile ground for technological, social and process innovation.
This production of knowledge directly benefits producers and users, and indirectly the whole society.

The main points we need to work on are:

* Implementing a migration plan and the gradual development of free software.

* Publishing and sharing Barcelona City Council’s software and contents under free software and content licenses.

* Making changes to public procurement to boost the creation, use and reuse of free and open source software.

* Requiring the use of open standards for the city’s technology, data and other information.

* Identifying development and/or migration opportunities to open architectures and systems in the short term.

The reference document for this topic is the Guide to Technological Sovereignty (see Annex 12.4).


== Responsible Data Strategy

Data are becoming increasingly important for cities because they enable cities to devise better public policies to combat social disparities, promote development and improve the quality of life for citizens.
The exponential growth of data and rapid evolution of technology promotes new service models to appear and causes profound changes in habits.
This context requires ICT organisations to take a flexible but constant approach to adapt and to how they manage the data they handle.

A new stage has been entered, where data are of considerable importance in the municipal and city environment, and there is a clear need for defining and operating a new municipal government data model that acts with sovereignty and which is cross-cutting across the entire City Council.

This involves organisational changes, as well as changes to functions and responsibilities, making it necessary to create a position with the City Council for a data manager or Chief Data Officer (CDO).

The main aspects to be examined further in this area are:

* New rules for data governance.

* Open architecture for data.

* From data to information, from information to city indicators.

* Ethical and responsible uses of data for innovation.

* Privacy and sovereignty.

The “Data Directive” for the City will be published with the next government measure on data management in Barcelona, where the policy for responsible and ethical data management will be established in a transversal way, with the municipal structure of data management, a Data Office and data managers, etc, and it will also include the processes and obligations for maximum compliance with the regulations for data protection and improving security.

== Transformation of Public Procurement of ICTs

As a cross-cutting policy to help the above-mentioned objectives and topics to be achieved, the usual processes and practices in purchasing technology must be changed to adapt to the agile methodologies to be implemented, to the transition to free software and open standards and to the new data strategy.

The new method for procuring technology will be open, transparent and more agile.
It will extend the range of providers that can access it, facilitating the procurement of solutions based on open source and open standards.
In addition, it will consider the aspects of data ownership and privacy, while observing compliance with legal regulations on data protection, including assessment of the ethical risks implied in using data.
As a result, we will have new procurement processes, technology acquisition guides and new digital services not just for potential providers but also for citizens and municipal procurement teams.

New approaches, rules and tools will be developed in order to have:

* Simpler procurement processes.

* Open procurement with more transparent processes.

* Guides for the procurement of solutions and services based on open technologies and the development of agile methodologies.

* A digital market platform to facilitate access for small and local suppliers.

The reference documents for this topic include the Public Procurement of Technology Guide (see Annex 12.6) and the Innovative Public Procurement Guide (see Annex 12.7).

== Capability, culture and management of organisational changes

This transformations will help train and develop existing teams, turning them into well-prepared internal teams with skills and capabilities to take full possession of the city’s digital services, data and architectural and procurement decisions.

These skills and capabilities will be supported by a series of behaviours and practices (organisational culture) and an service oriented organisational structure, facilitating team collaboration with prompt support from external teams that can complement and enrich the knowledge of internal staff while opening up new professional opportunities.

Figure 3 below shows the more important results that have already been achieved in the aforementioned areas:

image::open-digit-p25-guides-{lang}.svg[FIGURE 3,  align="center"]
